version: '3.9'

x-env-files: &env-files
  env_file:
    - ./docker/.env

services:
  mysql-management:
    image: mysql-cluster-local:8
    depends_on:
      - db
    <<: *env-files
    restart: always
    networks:
      - db-network
    command: ndb_mgmd

  mysql-data-node-1:
    image: mysql-cluster-local:8
    depends_on:
      - db
    <<: *env-files
    restart: always
    networks:
      - db-network
    command: ndbd
    volumes:
      - ./tmp/mysql/datanode-1:/var/lib/mysql

  mysql-data-node-2:
    image: mysql-cluster-local:8
    depends_on:
      - db
    <<: *env-files
    restart: always
    networks:
      - db-network
    command: ndbd
    volumes:
      - ./tmp/mysql/datanode-2:/var/lib/mysql

  db:
    image: mysql-cluster-local:8
    build:
      context: ./docker/mysql
    <<: *env-files
    restart: always
    networks:
      - db-network
    command: mysqld
    volumes:
      - ./docker/sql:/docker-entrypoint-initdb.d
    ports:
      - 3307:3306

  minio:
    image: minio/minio
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ROOT_USER=root
      - MINIO_ROOT_PASSWORD=password
    volumes:
      - ./tmp/storage:/data
    command: server /data --console-address ":9001"

networks:
  db-network:
