# This is a basic workflow to help you get started with Actions

name: Main

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the develop branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push to local registry
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: localhost:5000/lseg/thairod:latest
      -
        name: Inspect
        run: |
          docker buildx imagetools inspect localhost:5000/lseg/thairod:latest
        
        
      # -
      #   name: Login to GitLab
      #   uses: docker/login-action@v1
      #   with:
      #     registry: registry.gitlab.com
      #     username: ${{ secrets.GITLAB_USERNAME }}
      #     password: ${{ secrets.GITLAB_TOKEN }}
      # -
      #   name: Build
      #   id: docker_build
      #   uses: docker/build-push-action@v2
      #   with:
      #     push: true
      #     tags: 
      # -
      #   name: Image digest
      #   run: echo ${{ steps.docker_build.outputs.digest }}
    
    
  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo 'deploy to server'
    
